// Product families, not a live stock list. Confirm brands, variants and availability directly.
export const CATALOG = [
  {
    id: "aquariums",
    title: "Aquariums & custom builds",
    eyebrow: "TANKS & BUILDS",
    description: "From a first tank to a made-to-measure display, start with the right foundation.",
    image: "/assets/products/custom-4ft.jpg",
    alt: "Large custom aquarium",
    items: ["Ready-made tanks", "Custom aquariums", "Nano tanks", "Aquarium glass", "Stands & cabinets", "Lids & covers", "Sumps & overflow boxes", "Plumbing & fittings", "Installation accessories"],
  },
  {
    id: "equipment",
    title: "Aquarium equipment",
    eyebrow: "THE WORKING PARTS",
    description: "The filters, lighting and equipment that keep aquatic systems running.",
    image: "/assets/products/filtration.jpg",
    alt: "Aquarium filtration equipment",
    items: ["Internal filters", "Canister filters", "Hang-on filters", "Sponge filters", "Filter media", "Air pumps & aeration", "Water pumps & powerheads", "Aquarium lights", "Heaters & thermometers", "Chillers & cooling fans", "CO₂ equipment", "Test kits & maintenance tools", "Auto feeders & timers"],
  },
  {
    id: "aquascaping",
    title: "Aquascaping & decor",
    eyebrow: "BUILD THE LANDSCAPE",
    description: "Natural textures, planting materials and the finishing details for a living tank.",
    image: "/assets/products/driftwood.jpg",
    alt: "Driftwood for an aquascape",
    items: ["Aquarium soil", "Sand & gravel", "Stones & rocks", "Driftwood", "Aquatic plants", "Plant fertilisers", "Aquascaping tools", "Decor & backgrounds", "Pond liners & decor"],
  },
  {
    id: "fish",
    title: "Fish & aquatic care",
    eyebrow: "LIFE IN THE WATER",
    description: "Explore aquatic life and the food and care products around it.",
    image: "/assets/fishes.jpg",
    alt: "Freshwater fish in an aquarium",
    items: ["Freshwater fish", "Ornamental fish", "Goldfish & koi", "Betta fish", "Fish food", "Frozen & live food enquiries", "Water conditioners", "Fish health products", "Aquarium salt & treatments", "Pond supplies", "Breeding accessories"],
  },
  {
    id: "birds",
    title: "Birds & bird supplies",
    eyebrow: "FEATHERS & FLIGHT",
    description: "Ask about current bird availability and the essentials for their daily care.",
    image: "/assets/products/aviary.jpg",
    alt: "Bird in an aviary",
    items: ["Pet birds", "Exotic bird enquiries", "Parrots & macaws enquiries", "Budgies & lovebirds enquiries", "Bird food & seed", "Hand-feeding supplies", "Cages & aviaries", "Nest boxes & breeding supplies", "Perches & toys", "Bird care products"],
  },
  {
    id: "poultry",
    title: "Poultry & farm care",
    eyebrow: "FOR THE FLOCK",
    description: "A dedicated place for poultry enquiries, feed and practical care supplies.",
    image: "/assets/poultry-supply.webp",
    alt: "Illustrative hens and turkeys near feed supplies",
    items: ["Hens & poultry enquiries", "Turkey enquiries", "Chicks & duck enquiries", "Poultry feed", "Chick starter feed", "Feeders & drinkers", "Brooders & heat lamps", "Poultry supplements", "Poultry care products", "Housing accessories", "Bedding & litter"],
  },
  {
    id: "pets",
    title: "Everyday pet essentials",
    eyebrow: "FOR EVERY COMPANION",
    description: "Food, comfort, grooming and care for dogs, cats and small pets.",
    image: "/assets/products/dog-food.jpg",
    alt: "Pet food and feeding bowl",
    items: ["Dog food", "Cat food", "Treats & chews", "Supplements & vitamins", "Grooming products", "Shampoos & hygiene", "Beds & habitats", "Collars, leads & harnesses", "Bowls & feeders", "Toys & accessories", "Small-pet food & care", "Pet health products", "Litter & cleaning"],
  },
];

export const SHOP_HINTS = ["Filters", "Fish food", "Aquarium lights", "Driftwood", "Poultry feed"];

// Specific models with photographs matched to the product pages recorded in
// docs/product-photo-sources.json. These are enquiry examples, not live stock.
const model = (brand, name, group, kind, file, detail) => ({
  brand, name, group, kind, detail, image: `/assets/catalog/models/${file}`,
});
export const MODEL_PRODUCTS = [
  model("Blue Pet", "BL-773W Bio Top Filter", "equipment", "top", "blue-pet-bl-773w.webp", "Multi-section top filter · 6W · 500 L/h"),
  model("Blue Pet", "BL-774W 5-Stage Top Filter", "equipment", "top", "blue-pet-bl-774w.webp", "Five-stage top filter · 6W · 500 L/h"),
  model("Blue Pet", "BL-1880F Top Filter", "equipment", "top", "blue-pet-bl-1880f.png", "Aquarium top filter · ask for specifications"),
  model("SOBO", "WP-880F Top Filter", "equipment", "top", "sobo-wp-880f.webp", "Aquarium top filter · ask for specifications"),
  model("SOBO", "WP-1880F Top Filter", "equipment", "top", "sobo-wp-1880f.webp", "Aquarium top filter · ask for specifications"),
  model("SOBO", "WP-3880F Top Filter", "equipment", "top", "sobo-wp-3880f.webp", "Aquarium top filter · ask for specifications"),
  model("SOBO", "WP-607H Hang-On Filter", "equipment", "hang-on", "sobo-wp-607h.webp", "Hang-on-back aquarium filter"),
  model("SunSun", "HBL-803 Hang-On Filter", "equipment", "hang-on", "sunsun-hbl-803.webp", "Hang-on-back aquarium filter"),
  model("RS", "RS-800A Hang-On Filter", "equipment", "hang-on", "rs-800a.webp", "Hang-on-back aquarium filter"),
  model("SunSun", "HW-302 Canister Filter", "equipment", "canister", "sunsun-hw-302.webp", "External canister aquarium filter"),
  model("EHEIM", "Classic 250 Canister Filter", "equipment", "canister", "eheim-classic-250.jpg", "External canister aquarium filter"),
  model("Fluval", "107 Performance Canister Filter", "equipment", "canister", "fluval-107.jpg", "External canister filter · ask for specifications"),
  model("Blue Pet", "BL-200F Internal Filter", "equipment", "internal", "blue-pet-bl-200f.jpg", "Internal aquarium filter"),
  model("Blue Pet", "6005F Internal Filter", "equipment", "internal", "blue-pet-6005f.webp", "Internal aquarium filter"),
  model("SOBO", "FK-1002 Internal Filter", "equipment", "internal", "sobo-fk-1002.webp", "Internal aquarium filter"),
  model("Xinyou", "XY-002 Bio Sponge Filter", "equipment", "sponge", "xinyou-xy-002.webp", "Air-driven sponge aquarium filter"),
  model("Seachem", "Prime Water Conditioner", "fish", "conditioners", "seachem-prime.jpg", "Water conditioner · ask for available bottle size"),
  model("Seachem", "Stability Biofilter Supplement", "fish", "conditioners", "seachem-stability.jpg", "Biofilter supplement · ask for available bottle size"),
  model("API", "Stress Coat Water Conditioner", "fish", "conditioners", "api-stress-coat.jpg", "Water conditioner · ask for available bottle size"),
  model("Tetra", "Tetra Bits Complete Fish Food", "fish", "food", "tetra-bits.webp", "Fish food · ask for available pack size"),
  model("Taiyo", "Taiyo Bits Complete Fish Food", "fish", "food", "taiyo-bits.jpg", "Fish food · ask for available pack size"),
  model("ADA", "Aqua Soil Amazonia Ver.2", "aquascaping", "soil", "ada-amazonia-ver-2.jpg", "Aquascaping soil · ask for available bag size"),
  model("Royal Canin", "Mini Adult Dry Dog Food", "pets", "dog food", "royal-canin-mini-adult.jpg", "Small-breed adult dog food · ask for pack size"),
  model("Versele-Laga", "Prestige Big Parakeets Bird Food", "birds", "bird food", "versele-laga-parakeets.png", "Bird seed mix · ask for pack size"),
  model("Chihiros", "WRGB II 60 cm LED Light", "equipment", "lighting", "chihiros-wrgb-ii-60.jpg", "Aquarium LED light · ask for specifications"),
];

// Representative visuals for the browseable product families. Replace each with
// the exact SKU photograph when the supplier catalog and brand list arrive.
export const PRODUCT_PHOTOS = {
  "Ready-made tanks": "/assets/products/nano-cube.jpg",
  "Custom aquariums": "/assets/products/custom-4ft.jpg",
  "Nano tanks": "/assets/products/nano-cube.jpg",
  "Aquarium glass": "/assets/products/planted-2ft.jpg",
  "Stands & cabinets": "/assets/products/planted-2ft.jpg",
  "Lids & covers": "/assets/aquarium.jpg",
  "Sumps & overflow boxes": "/assets/products/filtration.jpg",
  "Plumbing & fittings": "/assets/products/filtration.jpg",
  "Installation accessories": "/assets/products/custom-4ft.jpg",
  "Internal & external filters": "/assets/products/filtration.jpg",
  "Internal filters": "/assets/products/filtration.jpg",
  "Canister filters": "/assets/products/filtration.jpg",
  "Hang-on filters": "/assets/products/filtration.jpg",
  "Sponge filters": "/assets/products/filtration.jpg",
  "Filter media": "/assets/products/filtration.jpg",
  "Air pumps & aeration": "/assets/aquarium.jpg",
  "Water pumps & powerheads": "/assets/products/filtration.jpg",
  "Aquarium lights": "/assets/products/custom-4ft.jpg",
  "Heaters & temperature care": "/assets/aquarium.jpg",
  "Heaters & thermometers": "/assets/aquarium.jpg",
  "Chillers & cooling fans": "/assets/products/filtration.jpg",
  "CO₂ equipment": "/assets/products/planted-2ft.jpg",
  "Test kits & maintenance tools": "/assets/products/filtration.jpg",
  "Auto feeders & timers": "/assets/products/filtration.jpg",
  "Aquarium soil": "/assets/products/aqua-soil.jpg",
  "Sand & gravel": "/assets/products/aqua-soil.jpg",
  "Stones & rocks": "/assets/aquarium.jpg",
  "Driftwood": "/assets/products/driftwood.jpg",
  "Aquatic plants": "/assets/products/anubias.jpg",
  "Plant fertilisers": "/assets/products/anubias.jpg",
  "Aquascaping tools": "/assets/products/planted-2ft.jpg",
  "Decor & backgrounds": "/assets/products/planted-2ft.jpg",
  "Pond liners & decor": "/assets/products/koi.jpg",
  "Freshwater fish": "/assets/fishes.jpg",
  "Ornamental fish": "/assets/products/discus.jpg",
  "Goldfish & koi": "/assets/products/koi.jpg",
  "Betta fish": "/assets/products/betta.jpg",
  "Fish food": "/assets/products/goldfish.jpg",
  "Frozen & live food enquiries": "/assets/products/goldfish.jpg",
  "Water conditioners": "/assets/products/filtration.jpg",
  "Fish health products": "/assets/products/betta.jpg",
  "Aquarium salt & treatments": "/assets/products/betta.jpg",
  "Pond supplies": "/assets/products/koi.jpg",
  "Breeding accessories": "/assets/products/goldfish.jpg",
  "Pet birds": "/assets/products/aviary.jpg",
  "Exotic bird enquiries": "/assets/products/aviary.jpg",
  "Parrots & macaws enquiries": "/assets/products/aviary.jpg",
  "Budgies & lovebirds enquiries": "/assets/products/aviary.jpg",
  "Bird food & seed": "/assets/products/aviary.jpg",
  "Hand-feeding supplies": "/assets/products/aviary.jpg",
  "Cages & aviaries": "/assets/products/aviary.jpg",
  "Nest boxes & breeding supplies": "/assets/products/aviary.jpg",
  "Perches & toys": "/assets/products/aviary.jpg",
  "Bird care products": "/assets/products/aviary.jpg",
  "Hens & poultry enquiries": "/assets/poultry-supply.webp",
  "Turkey enquiries": "/assets/poultry-supply.webp",
  "Chicks & duck enquiries": "/assets/poultry-supply.webp",
  "Poultry feed": "/assets/poultry-supply.webp",
  "Chick starter feed": "/assets/poultry-supply.webp",
  "Feeders & drinkers": "/assets/poultry-supply.webp",
  "Brooders & heat lamps": "/assets/poultry-supply.webp",
  "Poultry supplements": "/assets/poultry-supply.webp",
  "Poultry care products": "/assets/poultry-supply.webp",
  "Housing accessories": "/assets/poultry-supply.webp",
  "Bedding & litter": "/assets/poultry-supply.webp",
  "Dog & cat food": "/assets/products/dog-food.jpg",
  "Dog food": "/assets/products/dog-food.jpg",
  "Cat food": "/assets/persian-cat.jpg",
  "Treats & supplements": "/assets/products/dog-food.jpg",
  "Treats & chews": "/assets/products/dog-food.jpg",
  "Supplements & vitamins": "/assets/products/dog-food.jpg",
  "Grooming products": "/assets/products/grooming.jpg",
  "Shampoos & hygiene": "/assets/products/grooming.jpg",
  "Beds & habitats": "/assets/pet-lifestyle.jpg",
  "Collars, leads & harnesses": "/assets/golden-retriever.jpg",
  "Bowls & feeders": "/assets/products/dog-food.jpg",
  "Toys & accessories": "/assets/golden-retriever.jpg",
  "Small-pet food & care": "/assets/hamster.jpg",
  "Pet health products": "/assets/care-safety.jpg",
  "Litter & cleaning": "/assets/persian-cat.jpg",
};

// Generated, unbranded product photographs arranged in 4×4 contact sheets.
// A sheet entry gives each pictured supply type its own recognisable visual
// without implying that a particular model or package is currently stocked.
const sheet = (file, col, row) => ({ src: `/assets/catalog/${file}-sheet.png`, col, row });
export const PRODUCT_SHEETS = {
  "Plumbing & fittings": sheet("equipment", 1, 3),
  "Sumps & overflow boxes": sheet("equipment", 2, 3),
  "Internal filters": sheet("equipment", 0, 0),
  "Canister filters": sheet("equipment", 1, 0),
  "Hang-on filters": sheet("equipment", 2, 0),
  "Sponge filters": sheet("equipment", 3, 0),
  "Filter media": sheet("equipment", 0, 1),
  "Air pumps & aeration": sheet("equipment", 1, 1),
  "Water pumps & powerheads": sheet("equipment", 2, 1),
  "Aquarium lights": sheet("equipment", 3, 1),
  "Heaters & thermometers": sheet("equipment", 0, 2),
  "Chillers & cooling fans": sheet("equipment", 1, 2),
  "CO₂ equipment": sheet("equipment", 2, 2),
  "Test kits & maintenance tools": sheet("equipment", 3, 2),
  "Auto feeders & timers": sheet("equipment", 0, 3),
  "Aquarium soil": sheet("habitat", 0, 0),
  "Sand & gravel": sheet("habitat", 1, 0),
  "Stones & rocks": sheet("habitat", 2, 0),
  "Driftwood": sheet("habitat", 3, 0),
  "Aquatic plants": sheet("habitat", 0, 1),
  "Plant fertilisers": sheet("habitat", 1, 1),
  "Aquascaping tools": sheet("habitat", 2, 1),
  "Decor & backgrounds": sheet("habitat", 3, 1),
  "Fish food": sheet("habitat", 0, 2),
  "Water conditioners": sheet("habitat", 1, 2),
  "Bird food & seed": sheet("habitat", 2, 2),
  "Hand-feeding supplies": sheet("habitat", 3, 2),
  "Cages & aviaries": sheet("habitat", 0, 3),
  "Nest boxes & breeding supplies": sheet("habitat", 1, 3),
  "Perches & toys": sheet("habitat", 2, 3),
  "Bedding & litter": sheet("habitat", 3, 3),
  "Dog food": sheet("pet-poultry", 0, 0),
  "Cat food": sheet("pet-poultry", 1, 0),
  "Treats & chews": sheet("pet-poultry", 2, 0),
  "Supplements & vitamins": sheet("pet-poultry", 3, 0),
  "Grooming products": sheet("pet-poultry", 0, 1),
  "Shampoos & hygiene": sheet("pet-poultry", 1, 1),
  "Beds & habitats": sheet("pet-poultry", 2, 1),
  "Collars, leads & harnesses": sheet("pet-poultry", 3, 1),
  "Bowls & feeders": sheet("pet-poultry", 0, 2),
  "Toys & accessories": sheet("pet-poultry", 1, 2),
  "Small-pet food & care": sheet("pet-poultry", 2, 2),
  "Pet health products": sheet("pet-poultry", 3, 2),
  "Litter & cleaning": sheet("pet-poultry", 0, 3),
  "Poultry feed": sheet("pet-poultry", 1, 3),
  "Chick starter feed": sheet("pet-poultry", 1, 3),
  "Feeders & drinkers": sheet("pet-poultry", 2, 3),
  "Brooders & heat lamps": sheet("pet-poultry", 3, 3),
  "Poultry supplements": sheet("pet-poultry", 3, 0),
  "Ready-made tanks": sheet("tank-care", 0, 0),
  "Custom aquariums": sheet("tank-care", 1, 0),
  "Nano tanks": sheet("tank-care", 2, 0),
  "Aquarium glass": sheet("tank-care", 3, 0),
  "Stands & cabinets": sheet("tank-care", 0, 1),
  "Lids & covers": sheet("tank-care", 1, 1),
  "Installation accessories": sheet("tank-care", 2, 1),
  "Pond liners & decor": sheet("tank-care", 3, 1),
  "Frozen & live food enquiries": sheet("tank-care", 0, 2),
  "Fish health products": sheet("tank-care", 1, 2),
  "Aquarium salt & treatments": sheet("tank-care", 2, 2),
  "Pond supplies": sheet("tank-care", 3, 2),
  "Breeding accessories": sheet("tank-care", 0, 3),
  "Bird care products": sheet("tank-care", 1, 3),
  "Poultry care products": sheet("tank-care", 2, 3),
  "Housing accessories": sheet("tank-care", 3, 3),
};

// Real manufacturer product/range names are shown as examples to enquire
// about. They are not a statement that Dad's Pets currently stocks them.
const range = (brand, group, name, photo) => ({ brand, group, name, photo, detail: "Ask for the model, size, price and availability" });
export const BRANDED_PRODUCTS = [
  { name: "07 Series Canister Filters", brand: "Fluval", group: "equipment", detail: "107 · 207 · 307 · 407 models", photo: "Canister filters" },
  { name: "Classic External Filters", brand: "EHEIM", group: "equipment", detail: "Classic series · ask for model", photo: "Canister filters" },
  { name: "TetraMin Flakes", brand: "Tetra", group: "fish", detail: "Fish food · ask for pack size", photo: "Fish food" },
  { name: "Cichlid Gold", brand: "Hikari", group: "fish", detail: "Fish food · ask for pack size", photo: "Fish food" },
  { name: "Dog Nutrition Range", brand: "Royal Canin", group: "pets", detail: "Choose by age, breed and size", photo: "Dog food" },
  { name: "Dry Dog Food Range", brand: "Pedigree", group: "pets", detail: "Ask for life stage and pack size", photo: "Dog food" },
  { name: "Adult Dry Cat Food", brand: "Whiskas", group: "pets", detail: "Ask for flavour and pack size", photo: "Cat food" },
  { name: "Dog & Cat Food Range", brand: "Drools", group: "pets", detail: "Ask for formula and pack size", photo: "Dog food" },
  { name: "Bird Seed Mixes", brand: "Versele-Laga", group: "birds", detail: "Ask for bird type and pack size", photo: "Bird food & seed" },
  { name: "Poultry Feed Range", brand: "Venky's", group: "poultry", detail: "Ask for bird type and quantity", photo: "Poultry feed" },
  range("SOBO", "equipment", "Aquarium equipment range", "Internal filters"),
  range("SunSun", "equipment", "Aquarium equipment range", "Canister filters"),
  range("BOYU", "equipment", "Tanks & equipment range", "Ready-made tanks"),
  range("Resun", "equipment", "Aquarium equipment range", "Air pumps & aeration"),
  range("Hailea", "equipment", "Air pumps & equipment range", "Air pumps & aeration"),
  range("JBL", "fish", "Aquatic care range", "Water conditioners"),
  range("Sera", "fish", "Fish food & care range", "Fish food"),
  range("Chihiros", "equipment", "Aquarium lighting range", "Aquarium lights"),
  range("Aquael", "equipment", "Aquarium equipment range", "Internal filters"),
  range("API", "fish", "Water care range", "Water conditioners"),
  range("Ocean Free", "fish", "Aquatic care range", "Fish food"),
  range("Dymax", "equipment", "Aquarium equipment range", "Canister filters"),
  range("Taiyo", "fish", "Fish food range", "Fish food"),
  range("Optimum", "fish", "Fish food range", "Fish food"),
  range("AZOO", "fish", "Aquatic care range", "Water conditioners"),
  range("Tropica", "aquascaping", "Planted tank range", "Aquatic plants"),
  range("Dennerle", "aquascaping", "Aquascaping range", "Aquarium soil"),
  range("Farmina", "pets", "Dog & cat nutrition range", "Dog food"),
  range("ACANA", "pets", "Dog & cat food range", "Dog food"),
  range("ORIJEN", "pets", "Dog & cat food range", "Dog food"),
  range("Hill's", "pets", "Pet nutrition range", "Dog food"),
  range("Purina Pro Plan", "pets", "Dog & cat food range", "Dog food"),
  range("SmartHeart", "pets", "Pet food range", "Dog food"),
  range("Purepet", "pets", "Dog & cat food range", "Dog food"),
  range("Me-O", "pets", "Cat food range", "Cat food"),
  range("Sheba", "pets", "Cat food range", "Cat food"),
  range("IAMS", "pets", "Pet food range", "Dog food"),
  range("Chappi", "pets", "Dog food range", "Dog food"),
  range("Arden Grange", "pets", "Dog & cat food range", "Dog food"),
  range("Taste of the Wild", "pets", "Pet food range", "Dog food"),
  range("KONG", "pets", "Dog toys range", "Toys & accessories"),
  range("Trixie", "pets", "Pet accessories range", "Toys & accessories"),
  range("Beaphar", "pets", "Pet care range", "Pet health products"),
  range("PetSafe", "pets", "Pet accessories range", "Collars, leads & harnesses"),
  range("Wahl", "pets", "Grooming range", "Grooming products"),
  range("Savic", "pets", "Pet habitats range", "Beds & habitats"),
  range("Himalaya", "pets", "Pet care range", "Pet health products"),
  range("ZuPreem", "birds", "Bird food range", "Bird food & seed"),
  range("Vitapol", "birds", "Bird food range", "Bird food & seed"),
  range("Tunai", "birds", "Bird food range", "Bird food & seed"),
  range("Vetrina", "birds", "Bird care range", "Bird care products"),
  range("Kaytee", "birds", "Bird food range", "Bird food & seed"),
  range("RIO", "birds", "Bird food range", "Bird food & seed"),
  range("Vitakraft", "birds", "Bird food range", "Bird food & seed"),
  range("Godrej Agrovet", "poultry", "Poultry feed range", "Poultry feed"),
  range("Suguna", "poultry", "Poultry feed range", "Poultry feed"),
  range("SKM Feeds", "poultry", "Poultry feed range", "Poultry feed"),
];
